# Generated by Django 3.1.7 on 2021-03-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='shortquery',
            new_name='short_query',
        ),
    ]
